#ifndef unzip_ourex_unzip_h
#define unzip_ourex_unzip_h

#define unzClose ourex_zip_unzClose
#define unzCloseCurrentFile ourex_zip_unzCloseCurrentFile
#define unzGetCurrentFileInfo ourex_zip_unzGetCurrentFileInfo
#define unzGetFilePos ourex_zip_unzGetFilePos
#define unzGetGlobalComment ourex_zip_unzGetGlobalComment
#define unzGetGlobalInfo ourex_zip_unzGetGlobalInfo
#define unzGetLocalExtrafield ourex_zip_unzGetLocalExtrafield
#define unzGetOffset ourex_zip_unzGetOffset
#define unzGoToFilePos ourex_zip_unzGoToFilePos
#define unzGoToFirstFile ourex_zip_unzGoToFirstFile
#define unzGoToNextFile ourex_zip_unzGoToNextFile
#define unzLocateFile ourex_zip_unzLocateFile
#define unzOpen ourex_zip_unzOpen
#define unzOpen2 ourex_zip_unzOpen2
#define unzOpenCurrentFile ourex_zip_unzOpenCurrentFile
#define unzOpenCurrentFile2 ourex_zip_unzOpenCurrentFile2
#define unzOpenCurrentFile3 ourex_zip_unzOpenCurrentFile3
#define unzOpenCurrentFilePassword ourex_zip_unzOpenCurrentFilePassword
#define unzReadCurrentFile ourex_zip_unzReadCurrentFile
#define unzSetOffset ourex_zip_unzSetOffset
#define unzStringFileNameCompare ourex_zip_unzStringFileNameCompare
#define unzeof ourex_zip_unzeof
#define unztell ourex_zip_unztell

#define unz_copyright ourex_zip_unz_copyright
#define unzlocal_GetCurrentFileInfoInternal ourex_zip_unzlocal_GetCurrentFileInfoInternal
#define unzlocal_getByte ourex_zip_unzlocal_getByte
#define unzlocal_getLong ourex_zip_unzlocal_getLong

#include "_unzip.h"

#endif
