#ifndef zip_ourex_zip_h
#define zip_ourex_zip_h

#define zipClose ourex_zip_zipClose
#define zipCloseFileInZip ourex_zip_zipCloseFileInZip
#define zipCloseFileInZipRaw ourex_zip_zipCloseFileInZipRaw
#define zipFlushWriteBuffer ourex_zip_zipFlushWriteBuffer
#define zipOpen ourex_zip_zipOpen
#define zipOpen2 ourex_zip_zipOpen2
#define zipOpenNewFileInZip ourex_zip_zipOpenNewFileInZip
#define zipOpenNewFileInZip2 ourex_zip_zipOpenNewFileInZip2
#define zipOpenNewFileInZip3 ourex_zip_zipOpenNewFileInZip3
#define zipWriteInFileInZip ourex_zip_zipWriteInFileInZip

#define zip_copyright ourex_zip_zip_copyright
#define ziplocal_getByte ourex_zip_ziplocal_getByte
#define ziplocal_getLong ourex_zip_ziplocal_getLong

#include "_zip.h"

#endif
