#ifndef png_ourex_png_h
#define png_ourex_png_h

#define png_access_version_number        ourex_png_access_version_number       
#define png_build_gamma_table            ourex_png_build_gamma_table           
#define png_build_grayscale_palette      ourex_png_build_grayscale_palette     
#define png_calculate_crc                ourex_png_calculate_crc               
#define png_check_chunk_name             ourex_png_check_chunk_name            
#define png_check_keyword                ourex_png_check_keyword               
#define png_check_sig                    ourex_png_check_sig                   
#define png_chunk_error                  ourex_png_chunk_error                 
#define png_chunk_warning                ourex_png_chunk_warning               
#define png_combine_row                  ourex_png_combine_row                 
#define png_convert_from_struct_tm       ourex_png_convert_from_struct_tm      
#define png_convert_from_time_t          ourex_png_convert_from_time_t         
#define png_convert_to_rfc1123           ourex_png_convert_to_rfc1123          
#define png_crc_error                    ourex_png_crc_error                   
#define png_crc_finish                   ourex_png_crc_finish                  
#define png_crc_read                     ourex_png_crc_read                    
#define png_create_info_struct           ourex_png_create_info_struct          
#define png_create_read_struct           ourex_png_create_read_struct          
#define png_create_read_struct_2         ourex_png_create_read_struct_2        
#define png_create_struct                ourex_png_create_struct               
#define png_create_struct_2              ourex_png_create_struct_2             
#define png_create_write_struct          ourex_png_create_write_struct         
#define png_create_write_struct_2        ourex_png_create_write_struct_2       
#define png_data_freer                   ourex_png_data_freer                  
#define png_decompress_chunk             ourex_png_decompress_chunk            
#define png_default_flush                ourex_png_default_flush               
#define png_default_read_data            ourex_png_default_read_data           
#define png_default_write_data           ourex_png_default_write_data          
#define png_destroy_info_struct          ourex_png_destroy_info_struct         
#define png_destroy_read_struct          ourex_png_destroy_read_struct         
#define png_destroy_struct               ourex_png_destroy_struct              
#define png_destroy_struct_2             ourex_png_destroy_struct_2            
#define png_destroy_write_struct         ourex_png_destroy_write_struct        
#define png_do_background                ourex_png_do_background               
#define png_do_bgr                       ourex_png_do_bgr                      
#define png_do_chop                      ourex_png_do_chop                     
#define png_do_dither                    ourex_png_do_dither                   
#define png_do_expand                    ourex_png_do_expand                   
#define png_do_expand_palette            ourex_png_do_expand_palette           
#define png_do_gamma                     ourex_png_do_gamma                    
#define png_do_gray_to_rgb               ourex_png_do_gray_to_rgb              
#define png_do_invert                    ourex_png_do_invert                   
#define png_do_pack                      ourex_png_do_pack                     
#define png_do_packswap                  ourex_png_do_packswap                 
#define png_do_read_filler               ourex_png_do_read_filler              
#define png_do_read_interlace            ourex_png_do_read_interlace           
#define png_do_read_intrapixel           ourex_png_do_read_intrapixel          
#define png_do_read_invert_alpha         ourex_png_do_read_invert_alpha        
#define png_do_read_swap_alpha           ourex_png_do_read_swap_alpha          
#define png_do_read_transformations      ourex_png_do_read_transformations     
#define png_do_rgb_to_gray               ourex_png_do_rgb_to_gray              
#define png_do_shift                     ourex_png_do_shift                    
#define png_do_strip_filler              ourex_png_do_strip_filler             
#define png_do_swap                      ourex_png_do_swap                     
#define png_do_unpack                    ourex_png_do_unpack                   
#define png_do_unshift                   ourex_png_do_unshift                  
#define png_do_write_interlace           ourex_png_do_write_interlace          
#define png_do_write_intrapixel          ourex_png_do_write_intrapixel         
#define png_do_write_invert_alpha        ourex_png_do_write_invert_alpha       
#define png_do_write_swap_alpha          ourex_png_do_write_swap_alpha         
#define png_do_write_transformations     ourex_png_do_write_transformations    
#define png_error                        ourex_png_error                       
#define png_flush                        ourex_png_flush                       
#define png_free                         ourex_png_free                        
#define png_free_data                    ourex_png_free_data                   
#define png_free_default                 ourex_png_free_default                
#define png_get_IHDR                     ourex_png_get_IHDR                    
#define png_get_PLTE                     ourex_png_get_PLTE                    
#define png_get_bKGD                     ourex_png_get_bKGD                    
#define png_get_bit_depth                ourex_png_get_bit_depth               
#define png_get_cHRM                     ourex_png_get_cHRM                    
#define png_get_cHRM_fixed               ourex_png_get_cHRM_fixed              
#define png_get_channels                 ourex_png_get_channels                
#define png_get_color_type               ourex_png_get_color_type              
#define png_get_compression_buffer_size  ourex_png_get_compression_buffer_size 
#define png_get_compression_type         ourex_png_get_compression_type        
#define png_get_copyright                ourex_png_get_copyright               
#define png_get_error_ptr                ourex_png_get_error_ptr               
#define png_get_filter_type              ourex_png_get_filter_type             
#define png_get_gAMA                     ourex_png_get_gAMA                    
#define png_get_gAMA_fixed               ourex_png_get_gAMA_fixed              
#define png_get_hIST                     ourex_png_get_hIST                    
#define png_get_header_ver               ourex_png_get_header_ver              
#define png_get_header_version           ourex_png_get_header_version          
#define png_get_iCCP                     ourex_png_get_iCCP                    
#define png_get_image_height             ourex_png_get_image_height            
#define png_get_image_width              ourex_png_get_image_width             
#define png_get_int_32                   ourex_png_get_int_32                  
#define png_get_interlace_type           ourex_png_get_interlace_type          
#define png_get_io_ptr                   ourex_png_get_io_ptr                  
#define png_get_libpng_ver               ourex_png_get_libpng_ver              
#define png_get_mem_ptr                  ourex_png_get_mem_ptr                 
#define png_get_oFFs                     ourex_png_get_oFFs                    
#define png_get_pCAL                     ourex_png_get_pCAL                    
#define png_get_pHYs                     ourex_png_get_pHYs                    
#define png_get_pixel_aspect_ratio       ourex_png_get_pixel_aspect_ratio      
#define png_get_pixels_per_meter         ourex_png_get_pixels_per_meter        
#define png_get_progressive_ptr          ourex_png_get_progressive_ptr         
#define png_get_rgb_to_gray_status       ourex_png_get_rgb_to_gray_status      
#define png_get_rowbytes                 ourex_png_get_rowbytes                
#define png_get_rows                     ourex_png_get_rows                    
#define png_get_sBIT                     ourex_png_get_sBIT                    
#define png_get_sCAL                     ourex_png_get_sCAL                    
#define png_get_sPLT                     ourex_png_get_sPLT                    
#define png_get_sRGB                     ourex_png_get_sRGB                    
#define png_get_signature                ourex_png_get_signature               
#define png_get_tIME                     ourex_png_get_tIME                    
#define png_get_tRNS                     ourex_png_get_tRNS                    
#define png_get_text                     ourex_png_get_text                    
#define png_get_uint_16                  ourex_png_get_uint_16                 
#define png_get_uint_31                  ourex_png_get_uint_31                 
#define png_get_uint_32                  ourex_png_get_uint_32                 
#define png_get_unknown_chunks           ourex_png_get_unknown_chunks          
#define png_get_user_chunk_ptr           ourex_png_get_user_chunk_ptr          
#define png_get_user_height_max          ourex_png_get_user_height_max         
#define png_get_user_transform_ptr       ourex_png_get_user_transform_ptr      
#define png_get_user_width_max           ourex_png_get_user_width_max          
#define png_get_valid                    ourex_png_get_valid                   
#define png_get_x_offset_microns         ourex_png_get_x_offset_microns        
#define png_get_x_offset_pixels          ourex_png_get_x_offset_pixels         
#define png_get_x_pixels_per_meter       ourex_png_get_x_pixels_per_meter      
#define png_get_y_offset_microns         ourex_png_get_y_offset_microns        
#define png_get_y_offset_pixels          ourex_png_get_y_offset_pixels         
#define png_get_y_pixels_per_meter       ourex_png_get_y_pixels_per_meter      
#define png_handle_IEND                  ourex_png_handle_IEND                 
#define png_handle_IHDR                  ourex_png_handle_IHDR                 
#define png_handle_PLTE                  ourex_png_handle_PLTE                 
#define png_handle_as_unknown            ourex_png_handle_as_unknown           
#define png_handle_bKGD                  ourex_png_handle_bKGD                 
#define png_handle_cHRM                  ourex_png_handle_cHRM                 
#define png_handle_gAMA                  ourex_png_handle_gAMA                 
#define png_handle_hIST                  ourex_png_handle_hIST                 
#define png_handle_iCCP                  ourex_png_handle_iCCP                 
#define png_handle_oFFs                  ourex_png_handle_oFFs                 
#define png_handle_pCAL                  ourex_png_handle_pCAL                 
#define png_handle_pHYs                  ourex_png_handle_pHYs                 
#define png_handle_sBIT                  ourex_png_handle_sBIT                 
#define png_handle_sCAL                  ourex_png_handle_sCAL                 
#define png_handle_sPLT                  ourex_png_handle_sPLT                 
#define png_handle_sRGB                  ourex_png_handle_sRGB                 
#define png_handle_tEXt                  ourex_png_handle_tEXt                 
#define png_handle_tIME                  ourex_png_handle_tIME                 
#define png_handle_tRNS                  ourex_png_handle_tRNS                 
#define png_handle_unknown               ourex_png_handle_unknown              
#define png_handle_zTXt                  ourex_png_handle_zTXt                 
#define png_info_destroy                 ourex_png_info_destroy                
#define png_info_init                    ourex_png_info_init                   
#define png_info_init_3                  ourex_png_info_init_3                 
#define png_init_io                      ourex_png_init_io                     
#define png_init_read_transformations    ourex_png_init_read_transformations   
#define png_malloc                       ourex_png_malloc                      
#define png_malloc_default               ourex_png_malloc_default              
#define png_malloc_warn                  ourex_png_malloc_warn                 
#define png_memcpy_check                 ourex_png_memcpy_check                
#define png_memset_check                 ourex_png_memset_check                
#define png_permit_empty_plte            ourex_png_permit_empty_plte           
#define png_permit_mng_features          ourex_png_permit_mng_features         
#define png_process_IDAT_data            ourex_png_process_IDAT_data           
#define png_process_data                 ourex_png_process_data                
#define png_process_some_data            ourex_png_process_some_data           
#define png_progressive_combine_row      ourex_png_progressive_combine_row     
#define png_push_crc_finish              ourex_png_push_crc_finish             
#define png_push_crc_skip                ourex_png_push_crc_skip               
#define png_push_fill_buffer             ourex_png_push_fill_buffer            
#define png_push_handle_tEXt             ourex_png_push_handle_tEXt            
#define png_push_handle_unknown          ourex_png_push_handle_unknown         
#define png_push_handle_zTXt             ourex_png_push_handle_zTXt            
#define png_push_have_end                ourex_png_push_have_end               
#define png_push_have_info               ourex_png_push_have_info              
#define png_push_have_row                ourex_png_push_have_row               
#define png_push_process_row             ourex_png_push_process_row            
#define png_push_read_IDAT               ourex_png_push_read_IDAT              
#define png_push_read_chunk              ourex_png_push_read_chunk             
#define png_push_read_sig                ourex_png_push_read_sig               
#define png_push_read_tEXt               ourex_png_push_read_tEXt              
#define png_push_read_zTXt               ourex_png_push_read_zTXt              
#define png_push_restore_buffer          ourex_png_push_restore_buffer         
#define png_push_save_buffer             ourex_png_push_save_buffer            
#define png_read_data                    ourex_png_read_data                   
#define png_read_destroy                 ourex_png_read_destroy                
#define png_read_end                     ourex_png_read_end                    
#define png_read_filter_row              ourex_png_read_filter_row             
#define png_read_finish_row              ourex_png_read_finish_row             
#define png_read_image                   ourex_png_read_image                  
#define png_read_info                    ourex_png_read_info                   
#define png_read_init                    ourex_png_read_init                   
#define png_read_init_2                  ourex_png_read_init_2                 
#define png_read_init_3                  ourex_png_read_init_3                 
#define png_read_png                     ourex_png_read_png                    
#define png_read_push_finish_row         ourex_png_read_push_finish_row        
#define png_read_row                     ourex_png_read_row                    
#define png_read_rows                    ourex_png_read_rows                   
#define png_read_start_row               ourex_png_read_start_row              
#define png_read_transform_info          ourex_png_read_transform_info         
#define png_read_update_info             ourex_png_read_update_info            
#define png_reset_crc                    ourex_png_reset_crc                   
#define png_reset_zstream                ourex_png_reset_zstream               
#define png_save_int_32                  ourex_png_save_int_32                 
#define png_save_uint_16                 ourex_png_save_uint_16                
#define png_save_uint_32                 ourex_png_save_uint_32                
#define png_set_IHDR                     ourex_png_set_IHDR                    
#define png_set_PLTE                     ourex_png_set_PLTE                    
#define png_set_add_alpha                ourex_png_set_add_alpha               
#define png_set_bKGD                     ourex_png_set_bKGD                    
#define png_set_background               ourex_png_set_background              
#define png_set_bgr                      ourex_png_set_bgr                     
#define png_set_cHRM                     ourex_png_set_cHRM                    
#define png_set_cHRM_fixed               ourex_png_set_cHRM_fixed              
#define png_set_compression_buffer_size  ourex_png_set_compression_buffer_size 
#define png_set_compression_level        ourex_png_set_compression_level       
#define png_set_compression_mem_level    ourex_png_set_compression_mem_level   
#define png_set_compression_method       ourex_png_set_compression_method      
#define png_set_compression_strategy     ourex_png_set_compression_strategy    
#define png_set_compression_window_bits  ourex_png_set_compression_window_bits 
#define png_set_crc_action               ourex_png_set_crc_action              
#define png_set_dither                   ourex_png_set_dither                  
#define png_set_error_fn                 ourex_png_set_error_fn                
#define png_set_expand                   ourex_png_set_expand                  
#define png_set_expand_gray_1_2_4_to_8   ourex_png_set_expand_gray_1_2_4_to_8  
#define png_set_filler                   ourex_png_set_filler                  
#define png_set_filter                   ourex_png_set_filter                  
#define png_set_filter_heuristics        ourex_png_set_filter_heuristics       
#define png_set_flush                    ourex_png_set_flush                   
#define png_set_gAMA                     ourex_png_set_gAMA                    
#define png_set_gAMA_fixed               ourex_png_set_gAMA_fixed              
#define png_set_gamma                    ourex_png_set_gamma                   
#define png_set_gray_1_2_4_to_8          ourex_png_set_gray_1_2_4_to_8         
#define png_set_gray_to_rgb              ourex_png_set_gray_to_rgb             
#define png_set_hIST                     ourex_png_set_hIST                    
#define png_set_iCCP                     ourex_png_set_iCCP                    
#define png_set_interlace_handling       ourex_png_set_interlace_handling      
#define png_set_invalid                  ourex_png_set_invalid                 
#define png_set_invert_alpha             ourex_png_set_invert_alpha            
#define png_set_invert_mono              ourex_png_set_invert_mono             
#define png_set_keep_unknown_chunks      ourex_png_set_keep_unknown_chunks     
#define png_set_mem_fn                   ourex_png_set_mem_fn                  
#define png_set_oFFs                     ourex_png_set_oFFs                    
#define png_set_pCAL                     ourex_png_set_pCAL                    
#define png_set_pHYs                     ourex_png_set_pHYs                    
#define png_set_packing                  ourex_png_set_packing                 
#define png_set_packswap                 ourex_png_set_packswap                
#define png_set_palette_to_rgb           ourex_png_set_palette_to_rgb          
#define png_set_progressive_read_fn      ourex_png_set_progressive_read_fn     
#define png_set_read_fn                  ourex_png_set_read_fn                 
#define png_set_read_status_fn           ourex_png_set_read_status_fn          
#define png_set_read_user_chunk_fn       ourex_png_set_read_user_chunk_fn      
#define png_set_read_user_transform_fn   ourex_png_set_read_user_transform_fn  
#define png_set_rgb_to_gray              ourex_png_set_rgb_to_gray             
#define png_set_rgb_to_gray_fixed        ourex_png_set_rgb_to_gray_fixed       
#define png_set_rows                     ourex_png_set_rows                    
#define png_set_sBIT                     ourex_png_set_sBIT                    
#define png_set_sCAL                     ourex_png_set_sCAL                    
#define png_set_sPLT                     ourex_png_set_sPLT                    
#define png_set_sRGB                     ourex_png_set_sRGB                    
#define png_set_sRGB_gAMA_and_cHRM       ourex_png_set_sRGB_gAMA_and_cHRM      
#define png_set_shift                    ourex_png_set_shift                   
#define png_set_sig_bytes                ourex_png_set_sig_bytes               
#define png_set_strip_16                 ourex_png_set_strip_16                
#define png_set_strip_alpha              ourex_png_set_strip_alpha             
#define png_set_strip_error_numbers      ourex_png_set_strip_error_numbers     
#define png_set_swap                     ourex_png_set_swap                    
#define png_set_swap_alpha               ourex_png_set_swap_alpha              
#define png_set_tIME                     ourex_png_set_tIME                    
#define png_set_tRNS                     ourex_png_set_tRNS                    
#define png_set_tRNS_to_alpha            ourex_png_set_tRNS_to_alpha           
#define png_set_text                     ourex_png_set_text                    
#define png_set_text_2                   ourex_png_set_text_2                  
#define png_set_unknown_chunk_location   ourex_png_set_unknown_chunk_location  
#define png_set_unknown_chunks           ourex_png_set_unknown_chunks          
#define png_set_user_limits              ourex_png_set_user_limits             
#define png_set_user_transform_info      ourex_png_set_user_transform_info     
#define png_set_write_fn                 ourex_png_set_write_fn                
#define png_set_write_status_fn          ourex_png_set_write_status_fn         
#define png_set_write_user_transform_fn  ourex_png_set_write_user_transform_fn 
#define png_sig_cmp                      ourex_png_sig_cmp                     
#define png_start_read_image             ourex_png_start_read_image            
#define png_warning                      ourex_png_warning                     
#define png_write_IDAT                   ourex_png_write_IDAT                  
#define png_write_IEND                   ourex_png_write_IEND                  
#define png_write_IHDR                   ourex_png_write_IHDR                  
#define png_write_PLTE                   ourex_png_write_PLTE                  
#define png_write_bKGD                   ourex_png_write_bKGD                  
#define png_write_cHRM                   ourex_png_write_cHRM                  
#define png_write_cHRM_fixed             ourex_png_write_cHRM_fixed            
#define png_write_chunk                  ourex_png_write_chunk                 
#define png_write_chunk_data             ourex_png_write_chunk_data            
#define png_write_chunk_end              ourex_png_write_chunk_end             
#define png_write_chunk_start            ourex_png_write_chunk_start           
#define png_write_data                   ourex_png_write_data                  
#define png_write_destroy                ourex_png_write_destroy               
#define png_write_end                    ourex_png_write_end                   
#define png_write_filtered_row           ourex_png_write_filtered_row          
#define png_write_find_filter            ourex_png_write_find_filter           
#define png_write_finish_row             ourex_png_write_finish_row            
#define png_write_flush                  ourex_png_write_flush                 
#define png_write_gAMA                   ourex_png_write_gAMA                  
#define png_write_gAMA_fixed             ourex_png_write_gAMA_fixed            
#define png_write_hIST                   ourex_png_write_hIST                  
#define png_write_iCCP                   ourex_png_write_iCCP                  
#define png_write_image                  ourex_png_write_image                 
#define png_write_info                   ourex_png_write_info                  
#define png_write_info_before_PLTE       ourex_png_write_info_before_PLTE      
#define png_write_init                   ourex_png_write_init                  
#define png_write_init_2                 ourex_png_write_init_2                
#define png_write_init_3                 ourex_png_write_init_3                
#define png_write_oFFs                   ourex_png_write_oFFs                  
#define png_write_pCAL                   ourex_png_write_pCAL                  
#define png_write_pHYs                   ourex_png_write_pHYs                  
#define png_write_png                    ourex_png_write_png                   
#define png_write_row                    ourex_png_write_row                   
#define png_write_rows                   ourex_png_write_rows                  
#define png_write_sBIT                   ourex_png_write_sBIT                  
#define png_write_sCAL                   ourex_png_write_sCAL                  
#define png_write_sPLT                   ourex_png_write_sPLT                  
#define png_write_sRGB                   ourex_png_write_sRGB                  
#define png_write_sig                    ourex_png_write_sig                   
#define png_write_start_row              ourex_png_write_start_row             
#define png_write_tEXt                   ourex_png_write_tEXt                  
#define png_write_tIME                   ourex_png_write_tIME                  
#define png_write_tRNS                   ourex_png_write_tRNS                  
#define png_write_zTXt                   ourex_png_write_zTXt                  
#define png_zalloc                       ourex_png_zalloc                      
#define png_zfree                        ourex_png_zfree                       

#include "_png.h"

#endif
