#!/bin/sh -f

bush_home=../../bush

. ${bush_home}/args
. ${bush_home}/g4args

. ${bush_home}/app_header_use

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
use_archive=yes

if [ ${build_sdk_android} = "yes" ] ; then
  cppflags="${cppflags} -DEXLIB_ANDROID_MAIN_DO_STD_EXIT"
fi

if [ ${build_visual} = "yes" ] ; then
  cppflags="${cppflags} -bigobj"
  cppflags="${cppflags} -DNOMINMAX" #disconnect the cpp macros min,max in windows.h
fi

cppflags="${cppflags} -DEXLIB_HAS_PYTHIA8"

cppfiles="${cppfiles} ${exlib_home}/exlib/yacc/cexpr_lexer.cpp"
cppfiles="${cppfiles} ${exlib_home}/exlib/yacc/cexpr_eval.cpp"

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

use_geant4=yes
use_pythia8=yes
use_zip=yes
use_csz=yes

. ${bush_home}/use/csz
. ${bush_home}/use/zip

if [ ${build_geant4_10x} = "yes" ] ; then
  . ${bush_home}/use/geant4_10_03_p01
else
  . ${bush_home}/use/geant4
fi

. ${bush_home}/use/pythia8

. ${bush_home}/app_trailer_use

#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////
#//////////////////////////////////////////////////////

. ${bush_home}/app_trailer
