#!/bin/sh -f

bush_home=`pwd`/../../bush

. ${bush_home}/args
. ${bush_home}/g4args

save_dir=`pwd`

#/////////////////////////////////////////////////////////////
#/// cleanup comres //////////////////////////////////////////
#/////////////////////////////////////////////////////////////
${bush_home}/find_rm ../comres '*.*'
#/////////////////////////////////////////////////////////////
#/// get some files from ioda and put them in comres /////////
#/////////////////////////////////////////////////////////////

cd ..
from=../ioda/res

if [ ! -d ${from} ] ; then
  echo "directory ${from} not found. Continue to copy local res."
  exit
fi

files=""
files="${files} arialbd.ttf helveticabd.ttf courbd.ttf lucidagrandebd.ttf" #gui fonts.
files="${files} helvetica.ttf"
files="${files} stixgeneral.otf"

# cam panel :
files="${files} move2red.jpg crazyeye_run.jpg flip_flop.jpg"
files="${files} close.jpg edit.jpg edit_undo.jpg"

# main gui :
files="${files} go_home_large.jpg turn_around.jpg"
files="${files} movie_camera.jpg system_config_boot.jpg"

# rwc items :
files="${files} sidebar_photos.jpg stop_diaporama.jpg"
files="${files} cursor.jpg"

# main menu :
files="${files} files.jpg location_ftp.jpg"
files="${files} application_exit.jpg"
files="${files} edit_clear.jpg"
files="${files} move2red.jpg flip_flop.jpg"
files="${files} object_rotate_left.jpg stop_object_rotate_left.jpg"
files="${files} document_export.jpg"
files="${files} routing_step.jpg console.jpg tools.jpg"
files="${files} connect_to_wall.jpg"

files="${files} ioda_cube.jpg"
files="${files} set_current_region.jpg edit_plot.jpg"
files="${files} histo.jpg"
files="${files} package_edutainment.jpg"
files="${files} gun.jpg"
files="${files} edit_geom.jpg"
files="${files} clear_histo.jpg"
files="${files} white.jpg"

for file in ${files} ; do
  /bin/cp ${from}/${file} ./comres/.
done

/bin/cp ${from}/ioda.style ./comres/g4view.style

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/// copy app specific res files into comres /////////////////
#/////////////////////////////////////////////////////////////
files=""
files="${files} pythia_8170_xmldoc.zip"
files="${files} mu_plus_300_MeV.mac"
files="${files} g4view.scenarios"
files="${files} lhcbvelo.gdml lhcbhcal.gdml barrel.gdml"
files="${files} h_zz_4mu.cmnd"
files="${files} h_gamma_gamma.cmnd"
#files="${files} lht.gdml ilc.gdml"
files="${files} event.jpg stop_events.jpg vis_events.jpg clear_event.jpg"
files="${files} icon.jpg favicon.ico"
files="${files} g4view.ftp"

if [ ${build_geant4_10x} = "yes" ] ; then
  files="${files} g4emlow_6_50.zip g4ensdfstate_2_1.zip g4ndl_4_5.zip"
  files="${files} g4saiddata_1_1.zip photonevaporation_4_3_2.zip"
else # assume g4.9.5 :
  files="${files} g4emlow_6_23.zip"
fi

for file in ${files} ; do
  /bin/cp ../res/${file} ../comres/.
done

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ${bush_home}/and_app_res
. ${bush_home}/ios_app_res

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
if [ ${build_geant4_10x} = "yes" ] ; then
  /bin/rm -f ../comres/g4ndl_3_12.zip
fi    
