#!/bin/sh -f

zlib_home="uuuu"

ourex_pack_name=zlib

home_var="${ourex_pack_name}_home"
#ourex_pack_home="`eval echo \\$$home_var`"
ourex_pack_home="`eval echo \\${${home_var}}`"
echo ${ourex_pack_home}
exit

items="item_1 item_2 item_3 item_4"
found=
for item in ${items} ; do
  echo look_${item}
  if [ ${item} = item_2 ] ; then
    echo "item_2 found"
    found=${item}
    break
  fi
done
if [ "${found}" = "" ] ; then
  echo "not found."
  exit
else
  echo "found ${found}"
fi
