#ifndef expat_ourex_rename_h
#define expat_ourex_rename_h

#define expat_access_version_number        ourex_expat_access_version_number       
#define XML_ErrorString ourex_expat_XML_ErrorString
#define XML_GetCurrentByteIndex ourex_expat_XML_GetCurrentByteIndex
#define XML_GetCurrentLineNumber ourex_expat_XML_GetCurrentLineNumber
#define XML_GetErrorCode ourex_expat_XML_GetErrorCode
#define XML_Parse ourex_expat_XML_Parse
#define XML_ParserCreate ourex_expat_XML_ParserCreate
#define XML_ParserFree ourex_expat_XML_ParserFree
#define XML_SetCharacterDataHandler ourex_expat_XML_SetCharacterDataHandler
#define XML_SetElementHandler ourex_expat_XML_SetElementHandler
#define XML_SetUserData ourex_expat_XML_SetUserData

#define XML_DefaultCurrent ourex_expat_XML_DefaultCurrent
#define XML_ExternalEntityParserCreate ourex_expat_XML_ExternalEntityParserCreate
#define XML_GetBase ourex_expat_XML_GetBase
#define XML_GetBuffer ourex_expat_XML_GetBuffer
#define XML_GetCurrentByteCount ourex_expat_XML_GetCurrentByteCount
#define XML_GetCurrentColumnNumber ourex_expat_XML_GetCurrentColumnNumber
#define XML_GetSpecifiedAttributeCount ourex_expat_XML_GetSpecifiedAttributeCount
#define XML_ParseBuffer ourex_expat_XML_ParseBuffer
#define XML_ParserCreateNS ourex_expat_XML_ParserCreateNS
#define XML_SetBase ourex_expat_XML_SetBase
#define XML_SetCdataSectionHandler ourex_expat_XML_SetCdataSectionHandler
#define XML_SetCommentHandler ourex_expat_XML_SetCommentHandler
#define XML_SetDefaultHandler ourex_expat_XML_SetDefaultHandler
#define XML_SetDefaultHandlerExpand ourex_expat_XML_SetDefaultHandlerExpand
#define XML_SetEncoding ourex_expat_XML_SetEncoding
#define XML_SetExternalEntityRefHandler ourex_expat_XML_SetExternalEntityRefHandler
#define XML_SetExternalEntityRefHandlerArg ourex_expat_XML_SetExternalEntityRefHandlerArg
#define XML_SetNamespaceDeclHandler ourex_expat_XML_SetNamespaceDeclHandler
#define XML_SetNotStandaloneHandler ourex_expat_XML_SetNotStandaloneHandler
#define XML_SetNotationDeclHandler ourex_expat_XML_SetNotationDeclHandler
#define XML_SetProcessingInstructionHandler ourex_expat_XML_SetProcessingInstructionHandler
#define XML_SetUnknownEncodingHandler ourex_expat_XML_SetUnknownEncodingHandler
#define XML_SetUnparsedEntityDeclHandler ourex_expat_XML_SetUnparsedEntityDeclHandler
#define XML_UseParserAsHandlerArg ourex_expat_XML_UseParserAsHandlerArg

#define XmlGetUtf16InternalEncoding ourex_expat_XmlGetUtf16InternalEncoding
#define XmlGetUtf8InternalEncoding ourex_expat_XmlGetUtf8InternalEncoding
#define XmlInitEncoding ourex_expat_XmlInitEncoding
#define XmlInitUnknownEncoding ourex_expat_XmlInitUnknownEncoding
#define XmlParseXmlDecl ourex_expat_XmlParseXmlDecl
#define XmlPrologStateInit ourex_expat_XmlPrologStateInit
#define XmlSizeOfUnknownEncoding ourex_expat_XmlSizeOfUnknownEncoding
#define XmlUtf16Encode ourex_expat_XmlUtf16Encode
#define XmlUtf8Encode ourex_expat_XmlUtf8Encode
#define processXmlDecl ourex_expat_processXmlDecl

#define XML_ExpatVersion ourex_expat_XML_ExpatVersion
#define XML_ExpatVersionInfo ourex_expat_XML_ExpatVersionInfo
#define XML_FreeContentModel ourex_expat_XML_FreeContentModel
#define XML_GetFeatureList ourex_expat_XML_GetFeatureList
#define XML_GetIdAttributeIndex ourex_expat_XML_GetIdAttributeIndex
#define XML_GetInputContext ourex_expat_XML_GetInputContext
#define XML_GetParsingStatus ourex_expat_XML_GetParsingStatus
#define XML_MemFree ourex_expat_XML_MemFree
#define XML_MemMalloc ourex_expat_XML_MemMalloc
#define XML_MemRealloc ourex_expat_XML_MemRealloc
#define XML_ParserCreate_MM ourex_expat_XML_ParserCreate_MM
#define XML_ParserReset ourex_expat_XML_ParserReset
#define XML_ResumeParser ourex_expat_XML_ResumeParser
#define XML_SetAttlistDeclHandler ourex_expat_XML_SetAttlistDeclHandler
#define XML_SetDoctypeDeclHandler ourex_expat_XML_SetDoctypeDeclHandler
#define XML_SetElementDeclHandler ourex_expat_XML_SetElementDeclHandler
#define XML_SetEndCdataSectionHandler ourex_expat_XML_SetEndCdataSectionHandler
#define XML_SetEndDoctypeDeclHandler ourex_expat_XML_SetEndDoctypeDeclHandler
#define XML_SetEndElementHandler ourex_expat_XML_SetEndElementHandler
#define XML_SetEndNamespaceDeclHandler ourex_expat_XML_SetEndNamespaceDeclHandler
#define XML_SetEntityDeclHandler ourex_expat_XML_SetEntityDeclHandler
#define XML_SetParamEntityParsing ourex_expat_XML_SetParamEntityParsing
#define XML_SetReturnNSTriplet ourex_expat_XML_SetReturnNSTriplet
#define XML_SetSkippedEntityHandler ourex_expat_XML_SetSkippedEntityHandler
#define XML_SetStartCdataSectionHandler ourex_expat_XML_SetStartCdataSectionHandler
#define XML_SetStartDoctypeDeclHandler ourex_expat_XML_SetStartDoctypeDeclHandler
#define XML_SetStartElementHandler ourex_expat_XML_SetStartElementHandler
#define XML_SetStartNamespaceDeclHandler ourex_expat_XML_SetStartNamespaceDeclHandler
#define XML_SetXmlDeclHandler ourex_expat_XML_SetXmlDeclHandler
#define XML_StopParser ourex_expat_XML_StopParser
#define XML_UseForeignDTD ourex_expat_XML_UseForeignDTD

#define XML_ParserStruct ourex_expat_XML_ParserStruct
#define XML_Memory_Handling_Suite ourex_expat_XML_Memory_Handling_Suite

#define XmlGetUtf16InternalEncodingNS ourex_expat_XmlGetUtf16InternalEncodingNS
#define XmlGetUtf8InternalEncodingNS ourex_expat_XmlGetUtf8InternalEncodingNS
#define XmlInitEncodingNS ourex_expat_XmlInitEncodingNS
#define XmlInitUnknownEncodingNS ourex_expat_XmlInitUnknownEncodingNS
#define XmlParseXmlDeclNS ourex_expat_XmlParseXmlDeclNS
#define XmlPrologStateInitExternalEntity ourex_expat_XmlPrologStateInitExternalEntity
#define doParseXmlDecl ourex_expat_doParseXmlDecl

#endif
