#ifndef ourex_gl2ps_gl2ps_h
#define ourex_gl2ps_gl2ps_h

/* 
 gl2ps-1.3.2
 The gl2ps code is prefixed by ourex_ in order
 to avoid clashes with other gl2ps code that may come at link
 time from other channels.
*/

/* 1.2.3 */

#define gl2psSetBackgroundColor ourex_gl2psSetBackgroundColor

#define gl2psBeginPage ourex_gl2psBeginPage
#define gl2psEndPage ourex_gl2psEndPage
#define gl2psText ourex_gl2psText
#define gl2psEnable ourex_gl2psEnable
#define gl2psDisable ourex_gl2psDisable
#define gl2psPointSize ourex_gl2psPointSize
#define gl2psLineWidth ourex_gl2psLineWidth
#define gl2psNumShadeColors ourex_gl2psNumShadeColors
#define gl2psDrawPixels ourex_gl2psDrawPixels
#define gl2psBeginViewport ourex_gl2psBeginViewport
#define gl2psEndViewport ourex_gl2psEndViewport

#define gl2psMsg ourex_gl2psMsg
#define gl2psMalloc ourex_gl2psMalloc
#define gl2psRealloc ourex_gl2psRealloc
#define gl2psFree ourex_gl2psFree
#define gl2psListRealloc ourex_gl2psListRealloc
#define gl2psListCreate ourex_gl2psListCreate
#define gl2psListDelete ourex_gl2psListDelete
#define gl2psListAdd ourex_gl2psListAdd
#define gl2psListNbr ourex_gl2psListNbr
#define gl2psListPointer ourex_gl2psListPointer
#define gl2psListSort ourex_gl2psListSort
#define gl2psListAction ourex_gl2psListAction
#define gl2psListActionInverse ourex_gl2psListActionInverse
#define gl2psComparePointPlane ourex_gl2psComparePointPlane
#define gl2psPsca ourex_gl2psPsca
#define gl2psPvec ourex_gl2psPvec
#define gl2psNorm ourex_gl2psNorm
#define gl2psGetNormal ourex_gl2psGetNormal
#define gl2psGetPlane ourex_gl2psGetPlane
#define gl2psCutEdge ourex_gl2psCutEdge
#define gl2psCreateSplitPrimitive ourex_gl2psCreateSplitPrimitive
#define gl2psAddIndex ourex_gl2psAddIndex
#define gl2psGetIndex ourex_gl2psGetIndex
#define gl2psTestSplitPrimitive ourex_gl2psTestSplitPrimitive
#define gl2psSplitPrimitive ourex_gl2psSplitPrimitive
#define gl2psDivideQuad ourex_gl2psDivideQuad
#define gl2psCompareDepth ourex_gl2psCompareDepth
#define gl2psTrianglesFirst ourex_gl2psTrianglesFirst
#define gl2psFindRoot ourex_gl2psFindRoot
#define gl2psFreePrimitive ourex_gl2psFreePrimitive
#define gl2psAddPrimitiveInList ourex_gl2psAddPrimitiveInList
#define gl2psFreeBspTree ourex_gl2psFreeBspTree
#define gl2psGreater ourex_gl2psGreater
#define gl2psLess ourex_gl2psLess
#define gl2psBuildBspTree ourex_gl2psBuildBspTree
#define gl2psTraverseBspTree ourex_gl2psTraverseBspTree
#define gl2psGetPlaneFromPoints ourex_gl2psGetPlaneFromPoints
#define gl2psFreeBspImageTree ourex_gl2psFreeBspImageTree
#define gl2psCheckPoint ourex_gl2psCheckPoint
#define gl2psAddPlanesInBspTreeImage ourex_gl2psAddPlanesInBspTreeImage
#define gl2psCheckPrimitive ourex_gl2psCheckPrimitive
#define gl2psCreateSplitPrimitive2D ourex_gl2psCreateSplitPrimitive2D
#define gl2psSplitPrimitive2D ourex_gl2psSplitPrimitive2D
#define gl2psAddInImageTree ourex_gl2psAddInImageTree
#define gl2psAddInImage ourex_gl2psAddInImage
#define gl2psAddBoundaryInList ourex_gl2psAddBoundaryInList
#define gl2psBuildPolygonBoundary ourex_gl2psBuildPolygonBoundary
#define gl2psAddPolyPrimitive ourex_gl2psAddPolyPrimitive
#define gl2psGetVertex ourex_gl2psGetVertex
#define gl2psParseFeedbackBuffer ourex_gl2psParseFeedbackBuffer
#define gl2psSameColor ourex_gl2psSameColor
#define gl2psVertsSameColor ourex_gl2psVertsSameColor
#define gl2psPrintPostScriptHeader ourex_gl2psPrintPostScriptHeader
#define gl2psPrintPostScriptColor ourex_gl2psPrintPostScriptColor
#define gl2psResetPostScriptColor ourex_gl2psResetPostScriptColor
#define gl2psPrintPostScriptPrimitive ourex_gl2psPrintPostScriptPrimitive
#define gl2psPrintPostScriptFooter ourex_gl2psPrintPostScriptFooter
#define gl2psPrintTeXHeader ourex_gl2psPrintTeXHeader
#define gl2psPrintTeXPrimitive ourex_gl2psPrintTeXPrimitive
#define gl2psPrintTeXFooter ourex_gl2psPrintTeXFooter

#define gl2psPrintPostScriptBeginViewport ourex_gl2psPrintPostScriptBeginViewport
#define gl2psPrintPostScriptEndViewport ourex_gl2psPrintPostScriptEndViewport

#define gl2psWriteByte ourex_gl2psWriteByte
#define gl2psGetRGB ourex_gl2psGetRGB
#define gl2psPrintPostScriptPixmap ourex_gl2psPrintPostScriptPixmap
#define gl2psListReset ourex_gl2psListReset
#define gl2psAddInBspImageTree ourex_gl2psAddInBspImageTree
#define gl2psPrintPrimitives ourex_gl2psPrintPrimitives
#define gl2psPrintTeXBeginViewport ourex_gl2psPrintTeXBeginViewport
#define gl2psPrintTeXEndViewport ourex_gl2psPrintTeXEndViewport

#define gl2psAdaptVertexForBlending ourex_gl2psAdaptVertexForBlending
#define gl2psAssignTriangleProperties ourex_gl2psAssignTriangleProperties
#define gl2psBlendFunc ourex_gl2psBlendFunc
#define gl2psClosePDFDataStream ourex_gl2psClosePDFDataStream
#define gl2psCopyPixmap ourex_gl2psCopyPixmap
#define gl2psCopyPrimitive ourex_gl2psCopyPrimitive
#define gl2psCopyText ourex_gl2psCopyText
#define gl2psDrawImageMap ourex_gl2psDrawImageMap
#define gl2psFillTriangleFromPrimitive ourex_gl2psFillTriangleFromPrimitive
#define gl2psFreeImagemap ourex_gl2psFreeImagemap
#define gl2psFreePixmap ourex_gl2psFreePixmap
#define gl2psFreeText ourex_gl2psFreeText
#define gl2psOpenPDFDataStream ourex_gl2psOpenPDFDataStream
#define gl2psOpenPDFDataStreamWritePreface ourex_gl2psOpenPDFDataStreamWritePreface
#define gl2psPDFRectHull ourex_gl2psPDFRectHull
#define gl2psPDFgroupListDelete ourex_gl2psPDFgroupListDelete
#define gl2psPDFgroupListInit ourex_gl2psPDFgroupListInit
#define gl2psPDFgroupListWriteFontResources ourex_gl2psPDFgroupListWriteFontResources
#define gl2psPDFgroupListWriteGStateResources ourex_gl2psPDFgroupListWriteGStateResources
#define gl2psPDFgroupListWriteMainStream ourex_gl2psPDFgroupListWriteMainStream
#define gl2psPDFgroupListWriteObjects ourex_gl2psPDFgroupListWriteObjects
#define gl2psPDFgroupListWriteShaderResources ourex_gl2psPDFgroupListWriteShaderResources
#define gl2psPDFgroupListWriteVariableResources ourex_gl2psPDFgroupListWriteVariableResources
#define gl2psPDFgroupListWriteXObjectResources ourex_gl2psPDFgroupListWriteXObjectResources
#define gl2psPDFgroupObjectInit ourex_gl2psPDFgroupObjectInit
#define gl2psPDFstacksInit ourex_gl2psPDFstacksInit
#define gl2psPrintPDFBeginViewport ourex_gl2psPrintPDFBeginViewport
#define gl2psPrintPDFCatalog ourex_gl2psPrintPDFCatalog
#define gl2psPrintPDFCompressorType ourex_gl2psPrintPDFCompressorType
#define gl2psPrintPDFDataStreamLength ourex_gl2psPrintPDFDataStreamLength
#define gl2psPrintPDFEndViewport ourex_gl2psPrintPDFEndViewport
#define gl2psPrintPDFFillColor ourex_gl2psPrintPDFFillColor
#define gl2psPrintPDFFooter ourex_gl2psPrintPDFFooter
#define gl2psPrintPDFGSObject ourex_gl2psPrintPDFGSObject
#define gl2psPrintPDFHeader ourex_gl2psPrintPDFHeader
#define gl2psPrintPDFInfo ourex_gl2psPrintPDFInfo
#define gl2psPrintPDFLineWidth ourex_gl2psPrintPDFLineWidth
#define gl2psPrintPDFOpenPage ourex_gl2psPrintPDFOpenPage
#define gl2psPrintPDFPages ourex_gl2psPrintPDFPages
#define gl2psPrintPDFPixmap ourex_gl2psPrintPDFPixmap
#define gl2psPrintPDFPixmapStreamData ourex_gl2psPrintPDFPixmapStreamData
#define gl2psPrintPDFPrimitive ourex_gl2psPrintPDFPrimitive
#define gl2psPrintPDFShader ourex_gl2psPrintPDFShader
#define gl2psPrintPDFShaderExtGS ourex_gl2psPrintPDFShaderExtGS
#define gl2psPrintPDFShaderMask ourex_gl2psPrintPDFShaderMask
#define gl2psPrintPDFShaderSimpleExtGS ourex_gl2psPrintPDFShaderSimpleExtGS
#define gl2psPrintPDFShaderStreamData ourex_gl2psPrintPDFShaderStreamData
#define gl2psPrintPDFShaderStreamDataAlpha ourex_gl2psPrintPDFShaderStreamDataAlpha
#define gl2psPrintPDFShaderStreamDataCoord ourex_gl2psPrintPDFShaderStreamDataCoord
#define gl2psPrintPDFShaderStreamDataRGB ourex_gl2psPrintPDFShaderStreamDataRGB
#define gl2psPrintPDFStrokeColor ourex_gl2psPrintPDFStrokeColor
#define gl2psPrintPDFText ourex_gl2psPrintPDFText
#define gl2psPrintPostScriptImagemap ourex_gl2psPrintPostScriptImagemap
#define gl2psPrintf ourex_gl2psPrintf
#define gl2psPutPDFImage ourex_gl2psPutPDFImage
#define gl2psPutPDFText ourex_gl2psPutPDFText
#define gl2psSetLastColor ourex_gl2psSetLastColor
#define gl2psSortOutTrianglePDFgroup ourex_gl2psSortOutTrianglePDFgroup
#define gl2psSupportedBlendMode ourex_gl2psSupportedBlendMode
#define gl2psTextOpt ourex_gl2psTextOpt
#define gl2psWriteBigEndian ourex_gl2psWriteBigEndian
#define gl2psPrintDash ourex_gl2psPrintDash
#define gl2psRescaleAndOffset ourex_gl2psRescaleAndOffset

#define gl2psGetOptions ourex_gl2psGetOptions

/* 1.3.2 */

#define gl2psAddText ourex_gl2psAddText
#define gl2psComputeTightBoundingBox ourex_gl2psComputeTightBoundingBox
#define gl2psEPS ourex_gl2psEPS
#define gl2psEndPostScriptLine ourex_gl2psEndPostScriptLine
#define gl2psEndSVGLine ourex_gl2psEndSVGLine
#define gl2psGetFileExtension ourex_gl2psGetFileExtension
#define gl2psGetFormatDescription ourex_gl2psGetFormatDescription
#define gl2psInitTriangle ourex_gl2psInitTriangle
#define gl2psPDF ourex_gl2psPDF
#define gl2psPGF ourex_gl2psPGF
#define gl2psPGFTextAlignment ourex_gl2psPGFTextAlignment
#define gl2psPS ourex_gl2psPS
#define gl2psParseStipplePattern ourex_gl2psParseStipplePattern
#define gl2psPrintGzipFooter ourex_gl2psPrintGzipFooter
#define gl2psPrintGzipHeader ourex_gl2psPrintGzipHeader
#define gl2psPrintPDFFinalPrimitive ourex_gl2psPrintPDFFinalPrimitive
#define gl2psPrintPGFBeginViewport ourex_gl2psPrintPGFBeginViewport
#define gl2psPrintPGFColor ourex_gl2psPrintPGFColor
#define gl2psPrintPGFDash ourex_gl2psPrintPGFDash
#define gl2psPrintPGFEndViewport ourex_gl2psPrintPGFEndViewport
#define gl2psPrintPGFFinalPrimitive ourex_gl2psPrintPGFFinalPrimitive
#define gl2psPrintPGFFooter ourex_gl2psPrintPGFFooter
#define gl2psPrintPGFHeader ourex_gl2psPrintPGFHeader
#define gl2psPrintPGFPrimitive ourex_gl2psPrintPGFPrimitive
#define gl2psPrintPostScriptDash ourex_gl2psPrintPostScriptDash
#define gl2psPrintPostScriptFinalPrimitive ourex_gl2psPrintPostScriptFinalPrimitive
#define gl2psPrintSVGBeginViewport ourex_gl2psPrintSVGBeginViewport
#define gl2psPrintSVGDash ourex_gl2psPrintSVGDash
#define gl2psPrintSVGEndViewport ourex_gl2psPrintSVGEndViewport
#define gl2psPrintSVGFinalPrimitive ourex_gl2psPrintSVGFinalPrimitive
#define gl2psPrintSVGFooter ourex_gl2psPrintSVGFooter
#define gl2psPrintSVGHeader ourex_gl2psPrintSVGHeader
#define gl2psPrintSVGPixmap ourex_gl2psPrintSVGPixmap
#define gl2psPrintSVGPrimitive ourex_gl2psPrintSVGPrimitive
#define gl2psPrintSVGSmoothTriangle ourex_gl2psPrintSVGSmoothTriangle
#define gl2psPrintTeXFinalPrimitive ourex_gl2psPrintTeXFinalPrimitive
#define gl2psSVG ourex_gl2psSVG
#define gl2psSVGGetColorString ourex_gl2psSVGGetColorString
#define gl2psSVGGetCoordsAndColors ourex_gl2psSVGGetCoordsAndColors
#define gl2psSameColorThreshold ourex_gl2psSameColorThreshold
#define gl2psSamePosition ourex_gl2psSamePosition
#define gl2psSetOptions ourex_gl2psSetOptions
#define gl2psSpecial ourex_gl2psSpecial
#define gl2psTEX ourex_gl2psTEX
#define gl2psbackends ourex_gl2psbackends

#define gl2ps ourex_gl2ps

#include "_gl2ps.h"

#endif
