#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file bush.license for terms.

if [ $# != 1 ] ; then
  echo 'bush/add_license : give a file name.'
  exit
fi

/bin/cp $1 ./tmp_0   # to copy permission.

cat <<END > ./tmp_0
# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file bush.license for terms.
END
cat $1 >> ./tmp_0

/bin/mv ./tmp_0 $1


