#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file bush.license for terms.

bush_home=`dirname $0`

/bin/rm -f ./tmp_0
_find 'field_desc> s_v;' >> ./tmp_0

grep Found ./tmp_0 | awk '{print $6;}' | sed -e 's:"::g' > ./tmp_2

for item in $(cat ./tmp_2) ; do
  echo ${item}
  _upgrade -orders=${bush_home}/add_field.upgrade ${item}
  name="`basename ${item}`"
  sed -e "s:@@class@@:${name}:g" ${item} > ./tmp_0;/bin/mv ./tmp_0 ${item}
done

/bin/rm -f ./tmp_0 ./tmp_2
