#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file bush.license for terms.

if [ $# -ne 1 -a $# -ne 2 ] ; then
  echo "bush/check_app : one or two arguments expected"
  exit 1
fi

if [ "$1" = "" ] ; then
  echo "bush/check_app : no application given."
  exit 1
fi

#if [ "$2" = "" ] ; then
#  echo "bush/check_app : no comment given."
#  exit 1
#fi

old_IFS="${IFS}"
IFS=:
for check_app_path in $PATH ; do
  #echo Look ${check_app_path}
  if [ -f "${check_app_path}/$1" ] ; then
    #echo Found in ${check_app_path}
    IFS="${old_IFS}"    
    unset old_IFS
    exit 0
  fi
done
if [ "$2" != "" ] ; then echo $2; fi
IFS="${old_IFS}"
unset old_IFS
exit 1

