#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file bush.license for terms.

if [ $# != 2 ] ; then
  echo 'bush/find_rm : two arguments expected'
  exit
fi

#set -v 
#echo "debug $1"
#echo "debug $2"

# -L is to find under /tmp which is a symlink on a Mac.

find -L $1 -name $2 -print > ./tmp_find_rm
for file in $(cat ./tmp_find_rm) ; do
  #echo "bush/find_rm : rm ${file}"
  /bin/rm -R -f ${file}
done
/bin/rm -f ./tmp_find_rm
