#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file bush.license for terms.

if [ ! -d .git ] ; then
  echo "bush/gource : no .git found."
  exit
fi

# Using gource to visualize a repository's git history
#
# You'll need gource and ffmpeg (available through homebrew on OS X)
#
# Run this frim within a repository

gource_exe=/opt/local/bin/gource
ffmpeg_exe=/usr/local/ffmpeg/1.0/bin/ffmpeg

#gource_opts="${gource_opts} --title 'bush: making of a library'"
#gource_opts="${gource_opts} --logo MEDLogoBLK.jpg"
gource_opts="${gource_opts} --key --background 000000 --file-idle-time 30 --max-file-lag 1"
gource_opts="${gource_opts} --colour-images -a .1 --user-scale 1"
gource_opts="${gource_opts} --multi-sampling --bloom-multiplier 1 --bloom-intensity 0.75 --highlight-all-users"
gource_opts="${gource_opts} --stop-at-end --disable-progress --max-user-speed 400  -1280x720 -r 60 -s 0.25 -o -"
 
#ffmpeg_opts="${ffmpeg_opts} -preset medium -crf 9 -vcodec libx264"
ffmpeg_opts="${ffmpeg_opts} -y -r 60 -f image2pipe -vcodec ppm -i -"
ffmpeg_opts="${ffmpeg_opts} -pix_fmt yuv420p -threads 0 -bf 0 gource.mp4"

${gource_exe} ${gource_opts} | ${ffmpeg_exe} ${ffmpeg_opts} 

