#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file bush.license for terms.

# we expect that the compiler command (with options) is passed in one arg.

platform=
if [ $# != 1 ] ; then
  echo ${platform}
  exit
fi

bin_path=`dirname $0`

save_dir=`pwd`
cd ${bin_path}

cpp_compiler="`basename $1`"

if [ "${cpp_compiler}" = "vc++" ] ; then
  #NOTE : cl.exe prints the name of the compiled source file.
  #       We remove this output by sending it to /dev/null.
  cl.exe /nologo /MD /O2 /W3 /EHsc /GR ./cpp/platform.cpp 1> /dev/null
  platform="`./platform.exe`"
  platform="`echo ${platform} | sed -e 's: :\\\ :g'`"
  platform="`echo ${platform} | tr -d '\n\r'`"
  /bin/rm -f ./platform.obj ./platform.exe ./platform.exe.manifest
else
  ${cpp_compiler} -o platform_exe ./cpp/platform.cpp
  platform=`./platform_exe`
  /bin/rm -f ./platform_exe
fi

cd ${save_dir}

echo ${platform}
