#!/bin/sh -f

# Copyright (C) 2010, Guy Barrand. All rights reserved.
# See the file bush.license for terms.

if [ $# != 3 ] ; then
  echo 'bush/replace : three arguments expected : <old> <new> <file>'
  exit
fi

sed -e "s:$1:$2:g" $3 > ./tmp_0
/bin/mv ./tmp_0 $3
