#!/bin/sh -f

bush_home=`dirname $0`/..

#set -v

app="`${bush_home}/app_name`"
version="`${bush_home}/app_vers`"

#echo ${version}
#echo ${app}
#exit

doc_version=${version}_1

build_verbose=no
build_set_x=no
build_clear=no

build_args=""
while test $# -ge 1 ; do
  case $1 in
    -h) 
        echo "Options :"
        echo "  -clear : rm *.html, *.png, etc..."
        echo "  -x : execute with set -x."
        echo ""
        exit ;;
    -x) build_set_x=yes;build_args="${build_args} $1" ;;
    -clear) build_clear=yes ;;
    -*) echo "bush/doc/docbook_web : unknwon option : $1" ; exit ;;
  esac
  shift
done

if [ ${build_set_x} = yes ] ; then set -x; fi

save_dir=`pwd`

${bush_home}/check_app xsltproc 'xsltproc program not found.'
build_status=$?;if [ ${build_status} != 0 ] ; then exit ${build_status};fi

${bush_home}/check_app _h2docbook '_h2docbook program not found.'
build_status=$?;if [ ${build_status} != 0 ] ; then exit ${build_status};fi

docbook_xsl=/usr/local/docbook/docbook-xsl-1.78.1/html/docbook.xsl
docbook_xsl=/opt/local/share/xsl/docbook-xsl/html/docbook.xsl
if [ ! -f ${docbook_xsl} ] ; then
  echo "bush/doc/docbook_web : ${docbook_xsl} not found."
  exit
fi

cd ${bush_home}
bush_home=`pwd`
cd "${save_dir}"

web_dir="${bush_home}/../docs/${app}_doc/docbook_${doc_version}"
/bin/mkdir -p ${web_dir}

find "${web_dir}" -name '*.html' -type f -exec /bin/rm -f {} \;
find "${web_dir}" -name '*.png' -type f -exec /bin/rm -f {} \;

if [ "${build_clear}" = "yes" ] ; then exit; fi  

cd ./docbook

/bin/rm -f ./main.dtd

find ../h -name '*.h' -exec ${bush_home}/doc/h2xml ${docbook_xsl} ${web_dir} {} \;

params=
# for @verbinclude :
params="${params} --stringparam use.extensions 1"
params="${params} --stringparam textinsert.extension 1"

xsltproc ${params} --output ${web_dir}/main.html ${docbook_xsl} main.xml

/bin/rm -f ./tmp_images
find ../h -name '*.h' -exec ${bush_home}/doc/images {} \;
cat ./tmp_images | while read line; do
  name="`echo ${line} | awk '{print $3;}'`"
  /bin/cp ../images/${name} ${web_dir}/.
done
/bin/rm -f ./tmp_images

# NOTE : to produce pdf use :
#   UNIX> dblatex --fig-path=../images main.xml

cd "${save_dir}"
