#!/bin/sh -f

#write_apk=no
#while test $# -ge 1 ; do
#  case $1 in
#    -apk) write_apk=yes;;
#  esac
#  shift
#done

bush_home=`dirname $0`/..

#set -v

app="`${bush_home}/app_name`"
#version="`${bush_home}/app_vers`"

app_lower="`echo ${app} | tr '[:upper:]' '[:lower:]'`"

download_h=./h/download.h

download_inc=./h/download.inc

/bin/rm -f ${download_h}
/bin/rm -f ./tmp_files
/bin/rm -f ./tmp_dirs

download_area="${bush_home}/../docs/down_load/${app}"
if [ ! -d ${download_area} ] ; then
  echo "bush/doc/download_h : ${download_area} not a directory."
  exit
fi

find ${download_area} -maxdepth 1 -name '*' -type f -exec echo {} >> ./tmp_files \;
find ${download_area} -mindepth 1 -maxdepth 2 -name '*' -type d -exec echo {} >> ./tmp_dirs \;

echo '/**' >> ${download_h}
echo "@page ${app_lower}_download Download" >> ${download_h}

for file in $(cat ./tmp_files) ; do
  name="`basename ${file}`"
  if [ ${name} = .DS_Store ] ; then continue;fi
  line='- <a href="../../../down_load/'${app}'/'${name}'">'${name}'</a>'
  echo ${line} >> ${download_h}
done

echo '' >> ${download_h}

for dir in $(cat ./tmp_dirs) ; do
  #echo "directory ${dir} ..."
  dir_name="`basename ${dir}`"
  dir_name_title="${dir_name}"
  if [ "${dir_name_title}" = "_releases" ] ; then dir_name_title='releases'; fi
  dir_name_no_dot="`echo ${dir_name} | tr '.' '_'`"
  echo '@section '${app_lower}'_download_'${dir_name_no_dot}' '${dir_name_title} >> ${download_h}
  /bin/rm -f ./tmp_files
  find ${dir} -mindepth 1 -name '*' -type f -exec echo {} >> ./tmp_files \;
  for file in $(cat ./tmp_files) ; do
    name="`basename ${file}`"
    line='- <a href="../../../down_load/'${app}'/'${dir_name}'/'${name}'">'${name}'</a>'
    echo ${line} >> ${download_h}
  done
  echo "" >> ${download_h}
done

if [ -f ${download_inc} ] ; then
  cat ${download_inc} >> ${download_h}
fi

echo '' >> ${download_h}
echo '*/' >> ${download_h}

/bin/rm -f ./tmp_files ./tmp_dirs
