#!/bin/sh -f

bush_home=`dirname $0`/..

#set -v

app="`${bush_home}/app_name`"
version="`${bush_home}/app_vers`"

#echo ${version}
#echo ${app}
#exit

doc_version=${version}_1

build_verbose=no
build_set_x=no
build_clear=no

build_args=""
while test $# -ge 1 ; do
  case $1 in
    -h) 
        echo "Options :"
        echo "  -web : build user web pages."
        echo "  -clear : rm *.html, *.png, etc..."
        echo "  -x : execute with set -x."
        echo ""
        exit ;;
    -x) build_set_x=yes;build_args="${build_args} $1" ;;
    -clear) build_clear=yes ;;
    -*) echo "bush/doc/doxygen_web : unknwon option : $1" ; exit ;;
  esac
  shift
done

if [ ${build_set_x} = yes ] ; then set -x; fi

save_dir=`pwd`

${bush_home}/check_app doxygen 'doxygen program not found.'
build_status=$?;if [ ${build_status} != 0 ] ; then exit ${build_status};fi

cd ${bush_home}
bush_home=`pwd`
cd "${save_dir}"

web_dir="${bush_home}/../docs/${app}_doc/${doc_version}"
/bin/mkdir -p ${web_dir}

# To find Times.ttf :
DOTFONTPATH="${bush_home}/doc/fonts";export DOTFONTPATH

find "${web_dir}"  -name '*.html' -type f -exec /bin/rm -f {} \;
find "${web_dir}"  -name '*.png' -type f -exec /bin/rm -f {} \;
find "${web_dir}"  -name '*.dot' -type f -exec /bin/rm -f {} \;
find "${web_dir}"  -name '*.gif' -type f -exec /bin/rm -f {} \;
find "${web_dir}"  -name '*.css' -type f -exec /bin/rm -f {} \;

if [ "${build_clear}" = "yes" ] ; then exit; fi  

cd ./doxygen

if [ -f ./_Doxyfile ] ; then
  /bin/cp _Doxyfile Doxyfile
else
  /bin/cp ${bush_home}/doc/Doxyfile ./Doxyfile
  if [ ! -d ../inc ] ; then
    grep -v '../inc' ./Doxyfile > tmp_0;/bin/mv tmp_0 ./Doxyfile
  fi
fi

sed -e "s|@PROJECT_NAME@|${app}|g"             ./Doxyfile > ./tmp_0;/bin/mv ./tmp_0 ./Doxyfile
sed -e "s|@PROJECT_NUMBER@|${doc_version}|g"   ./Doxyfile > ./tmp_0;/bin/mv ./tmp_0 ./Doxyfile
sed -e "s|@OUTPUT_DIRECTORY@|${web_dir}|g" ./Doxyfile > ./tmp_0;/bin/mv ./tmp_0 ./Doxyfile

/bin/cp ${bush_home}/doc/header.html .
/bin/cp ${bush_home}/doc/footer.html .
/bin/cp ${bush_home}/doc/doxygen.css .
/bin/cp ${bush_home}/doc/table.css .

doxygen

/bin/rm -f Doxyfile header.html footer.html doxygen.css table.css

cd "${save_dir}"

/bin/rm -f "${web_dir}"/html/index.html

/bin/cp ./doxygen/index.html "${web_dir}"/.
/bin/cp ./doxygen/table.html "${web_dir}"/.
/bin/cp ${bush_home}/doc/table.css "${web_dir}"/html/.
if [ -f ./doxygen/index_lx.html ] ; then
  /bin/cp ./doxygen/index_lx.html "${web_dir}"/.
fi    

if [ -f ./doxygen/icon.png ] ; then
  /bin/cp ./doxygen/icon.png "${web_dir}"/.
else
  echo 'file ./doxygen/icon.png not found.'
fi    

# we take the doxygen.css of the 16.8. Recent
# doxygen.css makes that the table font is more
# bigger than the content.
/bin/cp ${bush_home}/doc/doxygen.css "${web_dir}"/.

cd "${save_dir}"

