#!/bin/sh -f

docbook_xsl=$1
web_dir=$2
file_h=$3

name="`echo ${file_h} | sed -e 's#\.h##g'`"
name="`basename ${name}`"

#echo $file_h
#echo ${name}
#exit

_h2docbook ${file_h} ./${name}.xml

params=
# for @verbinclude :
params="${params} --stringparam use.extensions 1"
params="${params} --stringparam textinsert.extension 1"

xsltproc ${params} --output ${web_dir}/${name}.html ${docbook_xsl} ./${name}.xml

cat <<END >> main.dtd
<!ENTITY ${name}_xml  SYSTEM "./${name}.xml">
END
