#define FT_MAKE_OPTION_SINGLE_OBJECT
#include "../../include/ourex_ft2build.h"
#include "afangles.c"
#include "afglobal.c"
#include "afhints.c"
#include "afdummy.c"
#include "aflatin.c"
#include "afloader.c"
#include "afmodule.c"
