UCRTContentRoot='C:\Program Files (x86)\Windows Kits\10\';export UCRTContentRoot
INCLUDE='C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE;C:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt;C:\Program Files (x86)\Windows Kits\8.1\include\shared;C:\Program Files (x86)\Windows Kits\8.1\include\um;C:\Program Files (x86)\Windows Kits\8.1\include\winrt;';export INCLUDE
OLDPWD='/usr/bin';export OLDPWD
curDir='C:\Program Files (x86)\Microsoft Visual C++ Build Tools\';export curDir
FrameworkVersion64='v4.0.30319';export FrameworkVersion64
WindowsLibPath='References\CommonConfiguration\Neutral';export WindowsLibPath
FrameworkDIR64='C:\WINDOWS\Microsoft.NET\Framework64';export FrameworkDIR64
VCTargetsPath='C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140\';export VCTargetsPath
Platform='X64';export Platform
CommandPromptType='Native';export CommandPromptType
FrameworkDir='C:\WINDOWS\Microsoft.NET\Framework64';export FrameworkDir
WindowsSDKLibVersion='winv6.3\';export WindowsSDKLibVersion
VCINSTALLDIR='C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\';export VCINSTALLDIR
LIB='C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;';export LIB
LIBPATH='C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64;C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319;C:\WINDOWS\Microsoft.NET\Framework64\;References\CommonConfiguration\Neutral;\Microsoft.VCLibs\14.0\References\CommonConfiguration\neutral;';export LIBPATH
PROMPT='$P$G';export PROMPT
WindowsSdkDir='C:\Program Files (x86)\Windows Kits\8.1\';export WindowsSdkDir
TERM='cygwin';export TERM
UCRTVersion='10.0.10240.0';export UCRTVersion
FrameworkVersion='v4.0.30319';export FrameworkVersion
UniversalCRTSdkDir='C:\Program Files (x86)\Windows Kits\10\';export UniversalCRTSdkDir
PATH='/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/MSBuild/14.0/bin/amd64:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64:/cygdrive/c/WINDOWS/Microsoft.NET/Framework64/v4.0.30319:/cygdrive/c/WINDOWS/Microsoft.NET/Framework64:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x64:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x86:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common Files/Intel/WirelessCommon:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Users/guyba_forni5u/AppData/Local/Microsoft/WindowsApps';export PATH
ORIGINAL_PATH='/cygdrive/c/Program Files (x86)/MSBuild/14.0/bin/amd64:/cygdrive/c/Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/amd64:/cygdrive/c/WINDOWS/Microsoft.NET/Framework64/v4.0.30319:/cygdrive/c/WINDOWS/Microsoft.NET/Framework64:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x64:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/bin/x86:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common Files/Intel/WirelessCommon:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Users/guyba_forni5u/AppData/Local/Microsoft/WindowsApps';export ORIGINAL_PATH
