#!/bin/sh -f

bush_home=../../../bush

. ${bush_home}/args
. ${bush_home}/ourex_header

if [ ${build_clang} = "yes" -o ${build_sdk_mac} = "yes" -o ${build_sdk_ios} = "yes" ] ; then
  # quiet warnings on ./source/jdphuff.c
  ccflags="${ccflags} -Wno-shift-negative-value"
  # quiet old clang (for exa 3.4) that does not have the upper warning.
  ccflags="${ccflags} -Wno-unknown-warning-option"
fi

if [ ${build_visual} = "yes" ] ; then
  libs="${libs} gdi32.lib user32.lib wsock32.lib" # to build the DLL.
fi

. ${bush_home}/ourex_generic
